import Logo from '@/app/_components/Logo'
import Navigation from '@/app/_components/Navigation'
import '@/app/_styles/globals.css'

export const metadata = {
  title: 'Oasis Hotel',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* <link href='./globals.css' rel='stylesheet' /> */}

      <body>
        <header>
          <Logo />
          <Navigation />
        </header>

        <main>{children}</main>
        <footer>Copyright by The Wild Programmer</footer>
      </body>
    </html>
  )
}
