import Logo from './components/Logo'
import Navigation from './components/Navigation'

export const metadata = {
  title: 'Oasis Hotel',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      {/* <link href='./globals.css' rel='stylesheet' /> */}

      <body>
        <header>
          <Logo />
          <Navigation />
        </header>

        <main>{children}</main>
        <footer className='text-red-700 text-xl'>
          Copyright by The Wild Programmer
        </footer>
      </body>
    </html>
  )
}
